site_name: IPFS Podcasting
theme:
  name: material
  icon:
    admonition:
      <type>: <icon>
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - content.code.annotate

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - footnotes
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - md_in_html

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/obdmpod

plugins:
  - search
